name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
      checks: write
      issues: read
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: false
          parallel: true
          install: false
          wait-on: 'https://www.saucedemo.com'
          wait-on-timeout: 120
          config-file: cypress.config.js
          group: 'UI Tests'
          spec: cypress/e2e/**/*.spec.js
        env:
          CYPRESS_USUARIO: ${{ secrets.CYPRESS_USUARIO }}
          CYPRESS_SENHA: ${{ secrets.CYPRESS_SENHA }}
          CYPRESS_USUARIOINCORRETO: ${{ secrets.CYPRESS_USUARIOINCORRETO }}
          CYPRESS_SENHAINCORRETA: ${{ secrets.CYPRESS_SENHAINCORRETA }}
          CYPRESS_USUARIOLOCKED: ${{ secrets.CYPRESS_USUARIOLOCKED }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.containers }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Generate test report
        if: always()
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/full_report.json
          npx marge cypress/reports/full_report.json -f report -o cypress/reports

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report-${{ matrix.containers }}
          path: cypress/reports
          if-no-files-found: ignore