name: Cypress Tests com GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  checks: write
  issues: read
  pull-requests: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Create Reports Directory
        run: |
          mkdir -p cypress/reports
          mkdir -p cypress/reports/html

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          wait-on: 'https://www.saucedemo.com'
          wait-on-timeout: 120
          record: true
          parallel: true
          group: 'UI Tests'
          spec: cypress/e2e/**/*.spec.js
          config: >
            pageLoadTimeout=180000,
            defaultCommandTimeout=10000,
            chromeWebSecurity=false
        env:
          CYPRESS_USUARIO: ${{ secrets.CYPRESS_USUARIO }}
          CYPRESS_SENHA: ${{ secrets.CYPRESS_SENHA }}
          CYPRESS_USUARIOINCORRETO: ${{ secrets.CYPRESS_USUARIOINCORRETO }}
          CYPRESS_SENHAINCORRETA: ${{ secrets.CYPRESS_SENHAINCORRETA }}
          CYPRESS_USUARIOLOCKED: ${{ secrets.CYPRESS_USUARIOLOCKED }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Generate Mochawesome Report
        if: always()
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/full_report.json
          npx marge cypress/reports/full_report.json -f report -o cypress/reports/html

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore
          compression-level: 9

      - name: Setup Pages for Report
        if: always() && github.event_name == 'push'
        uses: actions/configure-pages@v3

      - name: Upload Report to Pages
        if: always() && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v2
        with:
          path: cypress/reports/html

  deploy-report:
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: cypress-run
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2