name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
      checks: write
      issues: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Create Reports Directory
        run: |
          mkdir -p cypress/reports
          mkdir -p cypress/reports/html

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          wait-on: 'https://www.saucedemo.com'
          wait-on-timeout: 120
          record: true
          parallel: true
          group: 'UI Tests'
          spec: cypress/e2e/**/*.spec.js
          config: >
            pageLoadTimeout=180000,
            defaultCommandTimeout=10000,
            chromeWebSecurity=false
        env:
          CYPRESS_USUARIO: ${{ secrets.CYPRESS_USUARIO }}
          CYPRESS_SENHA: ${{ secrets.CYPRESS_SENHA }}
          CYPRESS_USUARIOINCORRETO: ${{ secrets.CYPRESS_USUARIOINCORRETO }}
          CYPRESS_SENHAINCORRETA: ${{ secrets.CYPRESS_SENHAINCORRETA }}
          CYPRESS_USUARIOLOCKED: ${{ secrets.CYPRESS_USUARIOLOCKED }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Generate Mochawesome Report
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/full_report.json
          npx marge cypress/reports/full_report.json -f report -o cypress/reports/html

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 30
          if-no-files-found: ignore
          compression-level: 9
